// ============================
// SANJEEV AI — Translation Engine
// ============================

const translations = {
  en: {
    // Topbar & Nav
    brandName: 'Sanjeev AI',
    navHome: 'Home',
    navScanner: 'Scanner',
    navTimeline: 'Timeline',
    navMood: 'Mood',

    // Home
    greeting: 'Namaste, Rahul',
    greetingSub: 'Your path to balance begins with mindful healing today.',
    safety: 'Safety',
    medSafetyScore: 'Medication Safety Score',
    scanPrescription: 'Scan Prescription',
    scanDesc: 'AI-powered analysis of all your prescriptions and medicines.',
    checkMood: 'Check Mood',
    moodDesc: 'Log your daily emotional and physical vitality balance.',
    viewAlerts: 'View Alerts',
    alertsDesc: '2 active interactions detected in your current protocol.',
    yourNextDose: 'Your Next Dose',
    withWarmWater: 'with warm water',
    markAsTaken: 'MARK AS TAKEN',
    holisticTools: 'Holistic Health Tools',
    symptomCheck: 'Symptom Check',
    mergedMeds: 'Merged Meds',
    caregiverHub: 'Caregiver Hub',
    weeklyReport: 'Weekly Report',
    interactionMap: 'Interaction Map',
    weeklyWisdom: 'Weekly Wisdom',
    insightTitle: 'The Alchemy of Brahmi for Mental Clarity',
    insightDesc: 'Learn how to pair herbal boosters with your morning meditation.',

    // Drug Interaction
    drugInteractionTitle: 'Drug Interaction Checker',
    drugInteractionSub: 'Comprehensive safety analysis for patient medication regimens.',
    patientContext: 'Patient Context',
    age: 'Age',
    knownAllergies: 'Known Allergies',
    kidneyIssue: 'Kidney Issue',
    liverIssue: 'Liver Issue',
    medicationList: 'Medication List',
    addAnother: 'Add Another',
    overallRiskScore: 'Overall Risk Score',
    low: 'Low',
    moderate: 'Moderate',
    high: 'High',
    critical: 'Critical',
    cascadePath: '1 cascade path',
    pairwise: '1 pairwise',
    cascadeDetected: 'Hidden Prescription Cascade Detected',
    gradeB: 'GRADE B',
    cascadeTechnical: 'Fluoxetine inhibits CYP2D6 enzyme blocking clearance of Metoprolol. Plasma levels rise — accumulation risk.',
    cascadeSimple: 'Fluoxetine stops your body from removing Metoprolol properly. Too much Metoprolol builds up in your blood. This can affect your heart. Tell your doctor immediately.',
    inhibitors: 'Inhibitors',
    affectedDrug: 'Affected Drug',
    safetyMapTitle: 'Safety Map™',
    liveNetwork: 'LIVE NETWORK',
    interactiveNetwork: 'Interactive drug interaction network',
    dragNodes: 'Drag nodes',
    scrollZoom: 'Scroll to zoom',
    cascadeDrug: 'Cascade drug',
    cautionDrug: 'Caution drug',
    safeDrug: 'Safe drug',
    cascadePathLegend: 'Cascade path',
    loadingMap: 'Loading Safety Map...',
    copyReport: 'Copy Report',
    exportPdf: 'Export PDF',
    alertDoctor: 'Alert Cardiologist & Psychiatrist',
    makeSimpler: 'Make Simpler',
    restoreMedical: 'Restore Medical Terms',

    // Scanner
    scannerTitle: 'Prescription Scanner',
    scannerSub: 'Point your camera at the prescription or upload a photo.',
    alignPrescription: 'Align prescription within frame',
    captureBtn: 'Capture',
    uploadBtn: 'Upload from Gallery',
    privacyNote: 'HIPAA-Ready Encryption',

    // ClearScript
    clearscriptTitle: 'ClearScript AI Extract',
    clearscriptSub: 'Our Three-Layer OCR Engine has digitized your messy prescription.',
    autoAccepted: 'Auto-Accepted (Clean read)',
    aiSuggestion: 'AI Suggestion:',
    confirm: 'Confirm',
    edit: 'Edit',
    manualFallback: 'Handwriting too messy. Manual fallback required.',
    runRiskAnalysis: 'Run Risk Analysis',

    // Timeline
    tlTitle: 'Your Health Journey',
    tlSub: 'Mapping your holistic progress and identifying vital correlations for your well-being.',
    tlAiAnalysis: 'AI Analysis',
    tlAiTitle: 'Mood changes correlate with Drug X start date.',
    tlAiDesc: 'Observation: 18 days after starting Drug X, a notable shift in emotional baseline was detected.',
    tlViewReport: 'View Full Report',
    tlMetricsTitle: 'Health Metrics',
    tlStress: 'STRESS',
    tlEnergy: 'ENERGY',
    tlRecovery: 'RECOVERY',
    tlItem1Date: 'March 12, 2024',
    tlItem1Title: 'Started Drug X',
    tlItem1Desc: 'Initial prescription: 50mg daily. Aimed at managing metabolic energy levels.',
    tlItem2Date: 'March 30, 2024',
    tlItem2Title: 'Mood Check-in: Low',
    tlItem2Desc: 'Reported persistent lethargy and decreased motivation levels.',
    tlItem3Date: 'April 05, 2024',
    tlItem3Title: 'Started Drug Y',
    tlItem3Desc: 'Supplementary dosage added to counteract metabolic fluctuations.',

    // Mood
    feelToday: 'How are you feeling today?',
    moodLow: 'Low',
    moodUneasy: 'Uneasy',
    moodNeutral: 'Neutral',
    moodCalm: 'Calm',
    moodHigh: 'High',
    anonMode: 'Anonymous Log Mode',
    addVoiceNote: 'Add a voice note',
    weeklyTrend: 'Weekly Mood Trend',
    trendDesc: 'Your energy is stabilizing in a healthy zone.',
    currentHarmonic: 'Current: Harmonic',
    holisticInsight: 'Holistic Insight',
    holisticDesc: 'Your midweek dip suggests an increase in stress. Try taking a short walk or practicing deep breathing tonight.',
    sleepSynergy: 'Sleep Synergy',
    sleepDesc: 'Mood peaks correlate with 8+ hours of rest. Aim for a 10 PM wind-down today.',
    days: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],

    // Risk Analysis
    riskTitle: 'Analysis Results',
    riskSub: 'We have analyzed your scanned medications against your health profile and existing regimen.',
    cautionTitle: 'Caution',
    cautionDesc: 'Potential risks detected in your current combination. Professional medical review is recommended before continuing dosage.',
    conflictAlert: 'Conflict Alert',
    conflictTitle: 'Interaction Detected: Drug A + Drug B',
    conflictDesc: 'These two medications together may cause drowsiness. Avoid driving while on both.',
    cascadeNote: 'Prescription Cascade Note',
    cascadeDesc: '"Drug B appears to be treating a side effect of Drug A. This pattern often suggests a \'cascade\' where new drugs are added to manage effects of the first, rather than addressing the root cause. Please consult your doctor."',
    takeAction: 'Take Action',
    takeActionDesc: 'Schedule a consultation with your primary physician to discuss these findings or find a holistic or safer alternative for better balance.',
    contactDoctor: 'Contact Doctor',
    shareReport: 'Share Report',
    guidanceTitle: 'Detailed Guidance',
    physioTitle: 'Physiological Alignment',
    physioDesc: 'The stimulating nature of Drug A may be causing the restlessness that Drug B is attempting to calm. Discussing a dosage adjustment with an expert could help.',
    timingTitle: 'Timing Optimization',
    timingDesc: 'To minimize interaction risks, take Drug A with your heaviest meal at noon, and consult if Drug B can be taken at night to align with your natural resting period.',

    // Alert
    alertTitle: 'Safety Alert',
    alertSub: 'Critical Medication Analysis',
    dangerTitle: 'Dangerous Interaction Detected',
    dangerDesc: 'Drug C and Drug D together pose a severe cardiac risk. Do not take them together.',
    sevCritical: 'Severity: Critical',
    cardiacImpact: 'Cardiac Impact',
    cardiacDesc: 'Potential for QT interval prolongation and severe arrhythmia.',
    detectTime: 'Detection Time',
    detectDesc: 'Interaction identified via scan 2 minutes ago.',
    notifyDoctor: 'Notify Doctor Now',
    emergencySos: 'Emergency SOS',
    clinicalDoc: 'Clinical Documentation',
    docDesc: 'Download a formal pharmacological report to share with your healthcare provider immediately.',
    genSafetyReport: 'Generate Safety Report for Doctor',

    // Caregiver
    cgTitle: 'Caregiver Hub',
    cgSub: 'Monitoring Rahul\'s holistic health and medication compliance.',
    cgMissedDose: 'Missed Dose Alert',
    sevMedium: 'Severity: Medium',
    missedDesc: 'Rahul missed the 08:30 AM dose of Metformin. Tap to call or send a gentle reminder.',
    weeklyCompliance: 'Weekly Compliance Tracker',
    today: 'TODAY',
    triggerSos: 'Trigger Shared Emergency SOS',
    callPrimary: 'Call Dr. Smith (Primary Physician)',
    emergencyCare: 'Emergency & Care Team',

    // Medications
    medsTitle: 'Unified Medications',
    medsSub: 'All your prescriptions from different doctors merged into one clear view.',
    showGeneric: 'Show Generic Names',
    aiUnifiedAlert: 'AI Check: No duplicates found across your 2 different prescribers. The brand-to-generic conversion shows all unique active ingredients.',
    takeAfD: 'Take 1 after dinner',
    takeInM: 'Take 1 in morning',

    // Symptoms
    symTitle: 'Symptom Checker',
    symSub: 'Describe how you feel, and our AI will check if it\'s related to your current medications.',
    tapToSpeak: 'Tap to Speak',
    voiceAvailable: 'Hands-free voice input available in English, Hindi, and Bengali.',
    simPatient: 'I\'ve been feeling a bit dizzy and my mouth is very dry since morning.',
    aiFound: 'AI Drug Correlation Found',
    aiSymptomMatch: 'Dizziness and dry mouth are common known side effects of the Lisinopril you started recently.',
    flagSymptoms: 'Flag Symptom to Doctor',

    // Report
    repTitle: 'Weekly Report',
    repSub: 'AI-generated summary of your health, ready to share with your doctor.',
    repSummary: 'Sanjeev AI Clinical Summary',
    repWeek: 'Week of March 18 - March 24',
    medChanges: 'Medication Changes',
    repAdd: 'Added Lisinopril (10mg) on Mar 19',
    repComp: '100% compliance on Metformin',
    moodSym: 'Mood & Symptom Correlations',
    moodSymDesc: 'Patient logged a 3-day trend of increased stress levels and dizziness, which historically correlates with the introduction of Lisinopril on Mar 19.',
    shareWithDr: 'Share PDF with Dr. Smith',

    // Profile
    navProfile: 'Profile',
    profileTitle: 'My Profile',
    profileSub: 'Manage your holistic health data and app preferences.',
    healthId: 'Health ID',
    personalInfo: 'Personal Info',
    age32: '32 Years',
    bloodType: 'Blood Type',
    weightTitle: 'Weight',
    weightLabel: '72 kg',
    medicalHistory: 'Medical History',
    historyDesc: 'View detailed logs of your past diagnoses and treatments.',
    settingsPrefs: 'Settings & Preferences',
    darkMode: 'Dark Mode',
    notifications: 'Push Notifications',
    dataPrivacy: 'Data Privacy',
    logout: 'Logout',
    manageButton: 'Manage'
  },

  hi: {
    brandName: 'संजीव AI',
    navHome: 'होम',
    navScanner: 'स्कैनर',
    navTimeline: 'टाइमलाइन',
    navMood: 'मूड',
    greeting: 'नमस्ते, राहुल',
    greetingSub: 'संतुलन की आपकी राह आज सचेत उपचार से शुरू होती है।',
    safety: 'सुरक्षा',
    medSafetyScore: 'दवा सुरक्षा स्कोर',
    scanPrescription: 'प्रिस्क्रिप्शन स्कैन करें',
    scanDesc: 'आपकी सभी दवाइयों का AI-संचालित विश्लेषण।',
    checkMood: 'मूड जांचें',
    moodDesc: 'अपनी दैनिक भावनात्मक और शारीरिक ऊर्जा दर्ज करें।',
    viewAlerts: 'अलर्ट देखें',
    alertsDesc: 'आपके वर्तमान प्रोटोकॉल में 2 सक्रिय अंतर्क्रियाएं पाई गईं।',
    yourNextDose: 'आपकी अगली खुराक',
    withWarmWater: 'गुनगुने पानी के साथ',
    markAsTaken: 'ली गई के रूप में चिह्नित करें',
    holisticTools: 'समग्र स्वास्थ्य उपकरण',
    symptomCheck: 'लक्षण जांच',
    mergedMeds: 'मिली हुई दवाएं',
    caregiverHub: 'देखभालकर्ता केंद्र',
    weeklyReport: 'साप्ताहिक रिपोर्ट',
    interactionMap: 'इंटरैक्शन मैप',
    weeklyWisdom: 'साप्ताहिक ज्ञान',
    insightTitle: 'मानसिक स्पष्टता के लिए ब्राह्मी का रसायन',
    insightDesc: 'जानें कि सुबह के ध्यान में हर्बल बूस्टर कैसे मिलाएं।',
    drugInteractionTitle: 'दवा अंतर्क्रिया जांचकर्ता',
    drugInteractionSub: 'रोगी दवा प्रणालियों का व्यापक सुरक्षा विश्लेषण।',
    patientContext: 'रोगी जानकारी',
    age: 'आयु',
    knownAllergies: 'ज्ञात एलर्जी',
    kidneyIssue: 'गुर्दे की समस्या',
    liverIssue: 'लिवर की समस्या',
    medicationList: 'दवाओं की सूची',
    addAnother: 'और जोड़ें',
    overallRiskScore: 'समग्र जोखिम स्कोर',
    low: 'कम',
    moderate: 'मध्यम',
    high: 'उच्च',
    critical: 'गंभीर',
    cascadePath: '1 कैस्केड पथ',
    pairwise: '1 जोड़ीवार',
    cascadeDetected: 'छिपा हुआ प्रिस्क्रिप्शन कैस्केड पकड़ा गया',
    gradeB: 'ग्रेड B',
    cascadeTechnical: 'Fluoxetine CYP2D6 एंजाइम को रोकता है जिससे Metoprolol की निकासी अवरुद्ध होती है। प्लाज्मा स्तर बढ़ता है — संचय जोखिम।',
    cascadeSimple: 'Fluoxetine आपके शरीर को Metoprolol को ठीक से हटाने से रोकता है। बहुत अधिक Metoprolol आपके खून में जमा हो जाता है। इससे आपके दिल पर असर पड़ सकता है। तुरंत अपने डॉक्टर को बताएं।',
    inhibitors: 'अवरोधक',
    affectedDrug: 'प्रभावित दवा',
    safetyMapTitle: 'सेफ्टी मैप™',
    liveNetwork: 'लाइव नेटवर्क',
    interactiveNetwork: 'इंटरैक्टिव दवा अंतर्क्रिया नेटवर्क',
    dragNodes: 'नोड्स खींचें',
    scrollZoom: 'ज़ूम करने के लिए स्क्रॉल करें',
    cascadeDrug: 'कैस्केड दवा',
    cautionDrug: 'सावधानी दवा',
    safeDrug: 'सुरक्षित दवा',
    cascadePathLegend: 'कैस्केड पथ',
    loadingMap: 'सेफ्टी मैप लोड हो रहा है...',
    copyReport: 'रिपोर्ट कॉपी करें',
    exportPdf: 'PDF निर्यात करें',
    alertDoctor: 'हृदय रोग विशेषज्ञ और मनोचिकित्सक को सतर्क करें',
    makeSimpler: 'सरल बनाएं',
    restoreMedical: 'चिकित्सा शब्द बहाल करें',
    scannerTitle: 'प्रिस्क्रिप्शन स्कैनर',
    scannerSub: 'अपना कैमरा प्रिस्क्रिप्शन पर लगाएं या फोटो अपलोड करें।',
    alignPrescription: 'प्रिस्क्रिप्शन को फ्रेम में रखें',
    captureBtn: 'कैप्चर',
    uploadBtn: 'गैलरी से अपलोड करें',
    privacyNote: 'HIPAA-तैयार एन्क्रिप्शन',
    clearscriptTitle: 'ClearScript AI अर्क',
    clearscriptSub: 'हमारे तीन-स्तरीय OCR इंजन ने आपके प्रिस्क्रिप्शन को डिजिटल कर दिया है।',
    autoAccepted: 'स्वतः स्वीकृत (स्पष्ट पठन)',
    aiSuggestion: 'AI सुझाव:',
    confirm: 'पुष्टि करें',
    edit: 'संपादित करें',
    manualFallback: 'हस्तलेख बहुत गंदा है। मैनुअल फॉलबैक आवश्यक।',
    runRiskAnalysis: 'जोखिम विश्लेषण चलाएं',
    
    // Translation keys for full coverage
    tlTitle: 'आपकी स्वास्थ्य यात्रा',
    tlSub: 'आपकी भलाई के लिए आपकी समग्र प्रगति का मानचित्रण और महत्वपूर्ण संबंधों की पहचान करना।',
    tlAiAnalysis: 'AI विश्लेषण',
    tlAiTitle: 'ड्रग X के शुरू होने की तारीख के साथ मूड में बदलाव का संबंध।',
    tlAiDesc: 'अवलोकन: ड्रग X शुरू करने के 18 दिन बाद, भावनात्मक आधाररेखा में उल्लेखनीय बदलाव देखा गया।',
    tlViewReport: 'पूरी रिपोर्ट देखें',
    tlMetricsTitle: 'स्वास्थ्य मेट्रिक्स',
    tlStress: 'तनाव',
    tlEnergy: 'ऊर्जा',
    tlRecovery: 'स्वास्थ्य लाभ',
    tlItem1Date: '12 मार्च, 2024',
    tlItem1Title: 'ड्रग X शुरू किया',
    tlItem1Desc: 'शुरुआती नुस्खा: रोजाना 50 मिलीग्राम। चयापचय ऊर्जा के स्तर को प्रबंधित करने का लक्ष्य।',
    tlItem2Date: '30 मार्च, 2024',
    tlItem2Title: 'मूड चेक-इन: कम',
    tlItem2Desc: 'लगातार सुस्ती और प्रेरणा के स्तर में कमी की सूचना दी।',
    tlItem3Date: '05 अप्रैल, 2024',
    tlItem3Title: 'ड्रग Y शुरू किया',
    tlItem3Desc: 'चयापचय में उतार-चढ़ाव का मुकाबला करने के लिए पूरक खुराक (सप्लीमेंट्री डोज़) जोड़ी गई।',

    feelToday: 'आज आप कैसा महसूस कर रहे हैं?',
    moodLow: 'उदास',
    moodUneasy: 'बेचैन',
    moodNeutral: 'तटस्थ',
    moodCalm: 'शांत',
    moodHigh: 'प्रसन्न',
    anonMode: 'अनाम लॉग मोड',
    addVoiceNote: 'वॉइस नोट जोड़ें',
    weeklyTrend: 'साप्ताहिक मूड ट्रेंड',
    trendDesc: 'आपकी ऊर्जा एक स्वस्थ क्षेत्र में स्थिर हो रही है।',
    currentHarmonic: 'वर्तमान: सामंजस्यपूर्ण',
    holisticInsight: 'समग्र अंतर्दृष्टि',
    holisticDesc: 'मिडवीक गिरावट तनाव में वृद्धि का सुझाव देती है। आज रात थोड़ी दूर टहलने या गहरी सांस लेने का अभ्यास करें।',
    sleepSynergy: 'नींद की तालमेल',
    sleepDesc: 'मूड 8+ घंटे के आराम के साथ सबसे अच्छा रहता है। आज रात 10 बजे तक सोने का लक्ष्य रखें।',
    days: ['सोम', 'मंगल', 'बुध', 'गुरु', 'शुक्र', 'शनि', 'रवि'],

    riskTitle: 'विश्लेषण परिणाम',
    riskSub: 'हमने आपके स्वास्थ्य प्रोफाइल और मौजूदा शासन (रेजिमेन) के विरुद्ध आपकी स्कैन की गई दवाओं का विश्लेषण किया है।',
    cautionTitle: 'सावधान',
    cautionDesc: 'आपके वर्तमान संयोजन में संभावित जोखिम पाए गए हैं। खुराक जारी रखने से पहले पेशेवर चिकित्सा समीक्षा की सलाह दी जाती है।',
    conflictAlert: 'अंतर्क्रिया चेतावनी',
    conflictTitle: 'अंतर्क्रिया पकड़ी गई: दवा A + दवा B',
    conflictDesc: 'ये दोनों दवाएं एक साथ उनींदापन पैदा कर सकती हैं। दोनों का सेवन करते समय वाहन चलाने से बचें।',
    cascadeNote: 'प्रिस्क्रिप्शन कैस्केड नोट',
    cascadeDesc: '"दवा B दवा A के दुष्प्रभाव का इलाज करती प्रतीत होती है। यह पैटर्न अक्सर एक \'कैस्केड\' का सुझाव देता है जहां मूल कारण को संबोधित करने के बजाय पहले के प्रभावों का प्रबंधन करने के लिए नई दवाएं जोड़ी जाती हैं। कृपया अपने डॉक्टर से परामर्श लें।"',
    takeAction: 'कार्रवाई करें',
    takeActionDesc: 'इन निष्कर्षों पर चर्चा करने के लिए अपने प्राथमिक चिकित्सक के साथ परामर्श निर्धारित करें या बेहतर संतुलन के लिए एक समग्र या सुरक्षित विकल्प खोजें।',
    contactDoctor: 'डॉक्टर से संपर्क करें',
    shareReport: 'रिपोर्ट साझा करें',
    guidanceTitle: 'विस्तृत मार्गदर्शन',
    physioTitle: 'शारीरिक संरेखण',
    physioDesc: 'दवा A की उत्तेजक प्रकृति बेचैनी पैदा कर सकती है जिसे दवा B शांत करने का प्रयास कर रही है। विशेषज्ञ से खुराक समायोजन पर चर्चा करने से मदद मिल सकती है।',
    timingTitle: 'समय अनुकूलन',
    timingDesc: 'अंतर्क्रिया जोखिमों को कम करने के लिए, दोपहर में सबसे भारी भोजन के साथ दवा A लें, और परामर्श करें कि क्या दवा B रात में ली जा सकती है ताकि आपकी प्राकृतिक आराम अवधि के साथ मेल खा सके।',
    
    alertTitle: 'सुरक्षा अलर्ट',
    alertSub: 'गंभीर दवा विश्लेषण',
    dangerTitle: 'खतरनाक अंतर्क्रिया पकड़ी गई',
    dangerDesc: 'ड्रग C और ड्रग D एक गंभीर हृदय जोखिम पैदा करते हैं। उन्हें एक साथ न लें।',
    sevCritical: 'गंभीरता: अत्यंत गंभीर',
    cardiacImpact: 'हृदय प्रभाव',
    cardiacDesc: 'QT अंतराल लम्बा होने और गंभीर अतालता की संभावना।',
    detectTime: 'पहचान का समय',
    detectDesc: '2 मिनट पहले स्कैन के माध्यम से अंतर्क्रिया की पहचान की गई थी।',
    notifyDoctor: 'डॉक्टर को अभी सूचित करें',
    emergencySos: 'आपातकालीन SOS',
    clinicalDoc: 'नैदानिक दस्तावेज़',
    docDesc: 'अपने स्वास्थ्य सेवा प्रदाता के साथ तुरंत साझा करने के लिए एक औपचारिक औषधीय (फार्माकोलॉजिकल) रिपोर्ट डाउनलोड करें।',
    genSafetyReport: 'डॉक्टर के लिए सुरक्षा रिपोर्ट तैयार करें',

    cgTitle: 'देखभालकर्ता केंद्र (केयरगिवर हब)',
    cgSub: 'राहुल के समग्र स्वास्थ्य और दवा अनुपालन (कम्प्लायंस) की निगरानी करना।',
    cgMissedDose: 'छूटी हुई खुराक अलर्ट',
    sevMedium: 'गंभीरता: मध्यम',
    missedDesc: 'राहुल ने सुबह 08:30 बजे की मेटफॉर्मिन की खुराक छोड़ दी है। कॉल करने या हल्का सा अनुस्मारक(रिमाइंडर) भेजने के लिए टैप करें।',
    weeklyCompliance: 'साप्ताहिक अनुपालन ट्रैकर',
    today: 'आज',
    triggerSos: 'साझा आपातकालीन SOS ट्रिगर करें',
    callPrimary: 'डॉ. स्मिथ को कॉल करें (प्राथमिक चिकित्सक)',
    emergencyCare: 'आपातकालीन और देखभाल टीम',

    medsTitle: 'एकीकृत दवाएं',
    medsSub: 'विभिन्न डॉक्टरों से आपके सभी नुस्खे एक स्पष्ट दृश्य (व्यू) में विलय हो गए हैं।',
    showGeneric: 'जेनरिक नाम दिखाएं',
    aiUnifiedAlert: 'AI जांच: आपके 2 अलग-अलग प्रिस्क्राइबर्स के बीच कोई डुप्लिकेट नहीं पाया गया। ब्रांड-टू-जेनेरिक रूपांतरण सभी अद्वितीय सक्रिय तत्व दिखाता है।',
    takeAfD: 'रात के खाने के बाद 1 लें',
    takeInM: 'सुबह 1 लें',

    symTitle: 'लक्षण चेकर (सिम्पटम चेकर)',
    symSub: 'वर्णन करें कि आप कैसा महसूस करते हैं, और हमारा AI जांच करेगा कि क्या यह आपकी वर्तमान दवाओं से संबंधित है।',
    tapToSpeak: 'बोलने के लिए टैप करें',
    voiceAvailable: 'हैंड्स-फ़्री ध्वनि इनपुट अंग्रेजी, हिंदी और बंगाली में उपलब्ध है।',
    simPatient: 'मुझे सुबह से थोड़ा चक्कर आ रहा है और मेरा मुँह बहुत सूखा है।',
    aiFound: 'AI दवा सहसंबंध (कोरिलेशन) मिला',
    aiSymptomMatch: 'चक्कर आना और मुंह सूखना हाल ही में आपके द्वारा शुरू किए गए लिसिनोप्रिल के सामान्य ज्ञात दुष्प्रभाव हैं।',
    flagSymptoms: 'डॉक्टर को लक्षण फ़्लैग करें',

    repTitle: 'साप्ताहिक रिपोर्ट',
    repSub: 'आपके स्वास्थ्य का AI-जनित सारांश, आपके डॉक्टर के साथ साझा करने के लिए तैयार है।',
    repSummary: 'संजीव AI नैदानिक सारांश',
    repWeek: '18 मार्च - 24 मार्च का सप्ताह',
    medChanges: 'दवा में बदलाव',
    repAdd: '19 मार्च को लिसिनोप्रिल (10 मिलीग्राम) जोड़ा गया',
    repComp: 'मेटफॉर्मिन पर 100% अनुपालन',
    moodSym: 'मूड और लक्षण संबंध',
    moodSymDesc: 'रोगी ने बढ़े हुए तनाव के स्तर और चक्कर आने के 3-दिवसीय रुझान को दर्ज किया है, जो ऐतिहासिक रूप से 19 मार्च को लिसिनोप्रिल की शुरुआत से संबंधित है।',
    shareWithDr: 'डॉ. स्मिथ के साथ पीडीएफ साझा करें',

    // Profile
    navProfile: 'प्रोफ़ाइल',
    profileTitle: 'मेरी प्रोफ़ाइल',
    profileSub: 'अपने समग्र स्वास्थ्य डेटा और ऐप प्राथमिकताओं को प्रबंधित करें।',
    healthId: 'स्वास्थ्य आईडी',
    personalInfo: 'व्यक्तिगत जानकारी',
    age32: '32 वर्ष',
    bloodType: 'रक्त समूह',
    weightTitle: 'वजन',
    weightLabel: '72 किग्रा',
    medicalHistory: 'चिकित्सा इतिहास',
    historyDesc: 'अपने पिछले निदान और उपचार के विस्तृत लॉग देखें।',
    settingsPrefs: 'सेटिंग्स और प्राथमिकताएं',
    darkMode: 'डार्क मोड',
    notifications: 'पुश सूचनाएं',
    dataPrivacy: 'डेटा गोपनीयता',
    logout: 'लॉग आउट',
    manageButton: 'प्रबंधित करें'
  },

  bn: {
    brandName: 'সঞ্জীব AI',
    navHome: 'হোম',
    navScanner: 'স্ক্যানার',
    navTimeline: 'টাইমলাইন',
    navMood: 'মেজাজ',
    greeting: 'নমস্কার, রাহুল',
    greetingSub: 'ভারসাম্যের পথ আজ সচেতন নিরাময় দিয়ে শুরু হয়।',
    safety: 'নিরাপত্তা',
    medSafetyScore: 'ওষুধ নিরাপত্তা স্কোর',
    scanPrescription: 'প্রেসক্রিপশন স্ক্যান করুন',
    scanDesc: 'আপনার সমস্ত ওষুধের AI-চালিত বিশ্লেষণ।',
    checkMood: 'মেজাজ পরীক্ষা করুন',
    moodDesc: 'আপনার দৈনন্দিন আবেগ এবং শারীরিক প্রাণশক্তি লিখুন।',
    viewAlerts: 'সতর্কতা দেখুন',
    alertsDesc: 'আপনার বর্তমান প্রোটোকলে ২টি সক্রিয় মিথস্ক্রিয়া সনাক্ত হয়েছে।',
    yourNextDose: 'আপনার পরের ডোজ',
    withWarmWater: 'গরম জলের সাথে',
    markAsTaken: 'নেওয়া হয়েছে হিসেবে চিহ্নিত করুন',
    holisticTools: 'সামগ্রিক স্বাস্থ্য সরঞ্জাম',
    symptomCheck: 'উপসর্গ পরীক্ষা',
    mergedMeds: 'একত্রিত ওষুধ',
    caregiverHub: 'পরিচর্যাকারী কেন্দ্র',
    weeklyReport: 'সাপ্তাহিক রিপোর্ট',
    interactionMap: 'ইন্টারঅ্যাকশন ম্যাপ',
    weeklyWisdom: 'সাপ্তাহিক জ্ঞান',
    insightTitle: 'মানসিক স্বচ্ছতার জন্য ব্রাহ্মীর রসায়ন',
    insightDesc: 'সকালের ধ্যানে ভেষজ বুস্টার কেমন করে যোগ করবেন তা শিখুন।',
    drugInteractionTitle: 'ওষুধ মিথস্ক্রিয়া পরীক্ষক',
    drugInteractionSub: 'রোগীর ওষুধ ব্যবস্থার ব্যাপক নিরাপত্তা বিশ্লেষণ।',
    patientContext: 'রোগীর তথ্য',
    age: 'বয়স',
    knownAllergies: 'পরিচিত অ্যালার্জি',
    kidneyIssue: 'কিডনি সমস্যা',
    liverIssue: 'লিভার সমস্যা',
    medicationList: 'ওষুধের তালিকা',
    addAnother: 'আরো যোগ করুন',
    overallRiskScore: 'সামগ্রিক ঝুঁকি স্কোর',
    low: 'কম',
    moderate: 'মাঝারি',
    high: 'উচ্চ',
    critical: 'জটিল',
    cascadePath: '১টি ক্যাসকেড পথ',
    pairwise: '১টি জোড়াবদ্ধ',
    cascadeDetected: 'লুকানো প্রেসক্রিপশন ক্যাসকেড সনাক্ত হয়েছে',
    gradeB: 'গ্রেড B',
    cascadeTechnical: 'Fluoxetine CYP2D6 এনজাইম বাধা দেয় যা Metoprolol এর ক্লিয়ারেন্স রোধ করে। প্লাজমা মাত্রা বাড়ে — সঞ্চয় ঝুঁকি।',
    cascadeSimple: 'Fluoxetine আপনার শরীরকে Metoprolol সঠিকভাবে অপসারণ করতে বাধা দেয়। অতিরিক্ত Metoprolol আপনার রক্তে জমা হয়। এটি আপনার হৃদয়ে প্রভাব ফেলতে পারে। অবিলম্বে আপনার ডাক্তারকে জানান।',
    inhibitors: 'বাধাদানকারী',
    affectedDrug: 'প্রভাবিত ওষুধ',
    safetyMapTitle: 'সেফটি ম্যাপ™',
    liveNetwork: 'লাইভ নেটওয়ার্ক',
    interactiveNetwork: 'ইন্টারেক্টিভ ওষুধ মিথস্ক্রিয়া নেটওয়ার্ক',
    dragNodes: 'নোড টানুন',
    scrollZoom: 'জুম করতে স্ক্রল করুন',
    cascadeDrug: 'ক্যাসকেড ওষুধ',
    cautionDrug: 'সতর্কতা ওষুধ',
    safeDrug: 'নিরাপদ ওষুধ',
    cascadePathLegend: 'ক্যাসকেড পথ',
    loadingMap: 'সেফটি ম্যাপ লোড হচ্ছে...',
    copyReport: 'রিপোর্ট কপি করুন',
    exportPdf: 'PDF রপ্তানি করুন',
    alertDoctor: 'হৃদরোগ বিশেষজ্ঞ ও মনোচিকিৎসককে সতর্ক করুন',
    makeSimpler: 'সহজ করুন',
    restoreMedical: 'চিকিৎসা পদ পুনরুদ্ধার করুন',
    scannerTitle: 'প্রেসক্রিপশন স্ক্যানার',
    scannerSub: 'আপনার ক্যামেরা প্রেসক্রিপশনের দিকে নির্দেশ করুন বা ছবি আপলোড করুন।',
    alignPrescription: 'প্রেসক্রিপশন ফ্রেমের মধ্যে রাখুন',
    captureBtn: 'ক্যাপচার',
    uploadBtn: 'গ্যালারি থেকে আপলোড',
    privacyNote: 'HIPAA-প্রস্তুত এনক্রিপশন',
    clearscriptTitle: 'ClearScript AI নির্যাস',
    clearscriptSub: 'আমাদের তিন-স্তরের OCR ইঞ্জিন আপনার প্রেসক্রিপশন ডিজিটাইজ করেছে।',
    autoAccepted: 'স্বয়ংক্রিয়ভাবে গৃহীত (পরিষ্কার পড়া)',
    aiSuggestion: 'AI পরামর্শ:',
    confirm: 'নিশ্চিত করুন',
    edit: 'সম্পাদনা করুন',
    manualFallback: 'হাতের লেখা খুব অস্পষ্ট। ম্যানুয়াল ফলব্যাক প্রয়োজন।',
    runRiskAnalysis: 'ঝুঁকি বিশ্লেষণ চালান',
    home: 'হোম',
    scanner: 'স্ক্যানার',
    timeline: 'টাইমলাইন',
    mood: 'মেজাজ',

    tlTitle: 'আপনার স্বাস্থ্য যাত্রা',
    tlSub: 'আপনার সুস্থতার জন্য সামগ্রিক অগ্রগতি ম্যাপিং এবং গুরুত্বপূর্ণ সম্পর্ক চিহ্নিত করা।',
    tlAiAnalysis: 'AI বিশ্লেষণ',
    tlAiTitle: 'ওষুধ X শুরু করার তারিখের সাথে মেজাজের পরিবর্তনের সম্পর্ক।',
    tlAiDesc: 'পর্যবেক্ষণ: ওষুধ X শুরু করার ১৮ দিন পর, মানসিক বেসলাইনে একটি উল্লেখযোগ্য পরিবর্তন লক্ষ্য করা গেছে।',
    tlViewReport: 'পূর্ণাঙ্গ রিপোর্ট দেখুন',
    tlMetricsTitle: 'স্বাস্থ্য মেট্রিক্স',
    tlStress: 'চাপ',
    tlEnergy: 'শক্তি',
    tlRecovery: 'পুনরুদ্ধার',
    tlItem1Date: '১২ মার্চ, ২০২৪',
    tlItem1Title: 'ওষুধ X শুরু',
    tlItem1Desc: 'প্রাথমিক প্রেসক্রিপশন: দৈনিক 50mg। মেটাবলিক শক্তির মাত্রা নিয়ন্ত্রণ করার লক্ষ্যে।',
    tlItem2Date: '৩০ মার্চ, ২০২৪',
    tlItem2Title: 'মেজাজ চেক-ইন: কম',
    tlItem2Desc: 'ক্রমাগত অলসতা এবং প্রেরণার মাত্রা হ্রাসের কথা জানিয়েছেন।',
    tlItem3Date: '০৫ এপ্রিল, ২০২৪',
    tlItem3Title: 'ওষুধ Y শুরু',
    tlItem3Desc: 'মেটাবলিক ওঠানামা মোকাবেলা করার জন্য সম্পূরক ডোজ যোগ করা হয়েছে।',

    feelToday: 'আজ আপনি কেমন বোধ করছেন?',
    moodLow: 'হতাশ',
    moodUneasy: 'অস্বস্তিকর',
    moodNeutral: 'নিরপেক্ষ',
    moodCalm: 'শান্ত',
    moodHigh: 'খুশি',
    anonMode: 'বেনামী লগ মোড',
    addVoiceNote: 'ভয়েস নোট যোগ করুন',
    weeklyTrend: 'সাপ্তাহিক মেজাজ ট্রেন্ড',
    trendDesc: 'আপনার শক্তি একটি সুস্থ অঞ্চলে স্থির হচ্ছে।',
    currentHarmonic: 'বর্তমান: সুরেলা',
    holisticInsight: 'সামগ্রিক অন্তর্দৃষ্টি',
    holisticDesc: 'মাঝ সপ্তাহের পতন মানসিক চাপের বৃদ্ধি নির্দেশ করে। আজ রাতে একটু হাঁটার চেষ্টা করুন বা গভীর শ্বাস-প্রশ্বাসের অনুশীলন করুন।',
    sleepSynergy: 'ঘুমের সমন্বয়',
    sleepDesc: '৮ ঘণ্টার বেশি বিশ্রামের সাথে মেজাজ সর্বোত্তম থাকে। রাত ১০ টার মধ্যে ঘুমানোর লক্ষ্য রাখুন।',
    days: ['সোম', 'মঙ্গল', 'বুধ', 'বৃহঃ', 'শুক্র', 'শনি', 'রবি'],

    riskTitle: 'বিশ্লেষণ ফলাফল',
    riskSub: 'আমরা আপনার স্বাস্থ্য প্রোফাইল এবং বিদ্যমান ওষুধের পদ্ধতির বিপরীতে আপনার স্ক্যান করা ওষুধগুলি বিশ্লেষণ করেছি।',
    cautionTitle: 'সতর্কতা',
    cautionDesc: 'আপনার বর্তমান সংমিশ্রণে সম্ভাব্য ঝুঁকি সনাক্ত করা হয়েছে। ডোজ চালিয়ে যাওয়ার আগে পেশাদার চিকিৎসা পর্যালোচনা সুপারিশ করা হয়।',
    conflictAlert: 'সংঘাত সতর্কতা',
    conflictTitle: 'মিথস্ক্রিয়া সনাক্ত: ওষুধ A + ওষুধ B',
    conflictDesc: 'এই দুটি ওষুধ একসঙ্গে তন্দ্রা সৃষ্টি করতে পারে। উভয় ওষুধ খাওয়ার সময় গাড়ি চালানো এড়িয়ে চলুন।',
    cascadeNote: 'প্রেসক্রিপশন ক্যাসকেড নোট',
    cascadeDesc: '"ওষুধ B-কে ওষুধ A-এর পার্শ্বপ্রতিক্রিয়ার চিকিৎসা করতে দেখা যাচ্ছে। এই প্যাটার্নটি প্রায়ই একটি \'ক্যাসকেড\' নির্দেশ করে যেখানে মূল কারণ সমাধানের পরিবর্তে প্রথমটির প্রভাবগুলি পরিচালনা করার জন্য নতুন ওষুধ যোগ করা হয়। অনুগ্রহ করে আপনার ডাক্তারের সাথে পরামর্শ করুন।"',
    takeAction: 'পদক্ষেপ নিন',
    takeActionDesc: 'এই ফলাফলগুলি নিয়ে আলোচনা করতে আপনার প্রাথমিক চিকিৎসকের সাথে পরামর্শের সময়সূচী নির্ধারণ করুন বা আরও ভাল ভারসাম্যের জন্য একটি সামগ্রিক বা নিরাপদ বিকল্প খুঁজুন।',
    contactDoctor: 'ডাক্তারকে কল করুন',
    shareReport: 'রিপোর্ট শেয়ার করুন',
    guidanceTitle: 'বিস্তারিত নির্দেশিকা',
    physioTitle: 'শারীরবৃত্তীয় সারিবদ্ধকরণ',
    physioDesc: 'ওষুধ A এর উদ্দীপক প্রকৃতি অস্থিরতা সৃষ্টি করতে পারে যা ওষুধ B শান্ত করার চেষ্টা করছে। একজন বিশেষজ্ঞের সাথে ডোজ সমন্বয় নিয়ে আলোচনা করা সাহায্য করতে পারে।',
    timingTitle: 'সময়ের অপ্টিমাইজেশন',
    timingDesc: 'মিথস্ক্রিয়া ঝুঁকি কমানোর জন্য, দুপুরে আপনার সবচেয়ে ভারী খাবারের সাথে ওষুধ A নিন, এবং আপনার প্রাকৃতিক বিশ্রামের সময়ের সাথে সারিবদ্ধ করার জন্য রাতে ওষুধ B নেওয়া যেতে পারে কিনা তা পরামর্শ করুন।',

    alertTitle: 'নিরাপত্তা সতর্কতা',
    alertSub: 'গুরুতর ঔষধ বিশ্লেষণ',
    dangerTitle: 'বিপজ্জনক মিথস্ক্রিয়া সনাক্ত',
    dangerDesc: 'ওষুধ C এবং ওষুধ D একত্রে তীব্র হৃদরোগের ঝুঁকি সৃষ্টি করে। এগুলো একসাথে গ্রহণ করবেন না।',
    sevCritical: 'তীব্রতা: অত্যন্ত গুরুতর',
    cardiacImpact: 'কার্ডিয়াক প্রভাব',
    cardiacDesc: 'সম্ভাব্য QT ব্যবধান দীর্ঘায়িতকরণ এবং গুরুতর অ্যারিথমিয়া।',
    detectTime: 'সনাক্তকরণের সময়',
    detectDesc: 'স্ক্যানের মাধ্যমে ২ মিনিট আগে মিথস্ক্রিয়া চিহ্নিত করা হয়েছে।',
    notifyDoctor: 'ডাক্তারকে এখনই জানান',
    emergencySos: 'জরুরি SOS',
    clinicalDoc: 'ক্লিনিকাল ডকুমেন্টেশন',
    docDesc: 'আপনার স্বাস্থ্যসেবা প্রদানকারীর সাথে অবিলম্বে শেয়ার করার জন্য একটি আনুষ্ঠানিক ফার্মাকোলজিক্যাল রিপোর্ট ডাউনলোড করুন।',
    genSafetyReport: 'ডাক্তারের জন্য নিরাপত্তা রিপোর্ট তৈরি করুন',

    cgTitle: 'পরিচর্যাকারী কেন্দ্র',
    cgSub: 'রাহুলের সামগ্রিক স্বাস্থ্য এবং ঔষধ সম্মতির পর্যবেক্ষণ।',
    cgMissedDose: 'মিসড ডোজ সতর্কতা',
    sevMedium: 'তীব্রতা: মাঝারি',
    missedDesc: 'রাহুল সকাল ০৮:৩০-এর মেটফরমিনের ডোজ মিস করেছে। কল করতে বা এলার্ম পাঠাতে ট্যাপ করুন।',
    weeklyCompliance: 'সাপ্তাহিক কমপ্লায়েন্স ট্র্যাকার',
    today: 'আজ',
    triggerSos: 'শেয়ার করা জরুরি SOS ট্রিগার করুন',
    callPrimary: 'ডাঃ স্মিথকে কল করুন (প্রাথমিক চিকিৎসক)',
    emergencyCare: 'জরুরী এবং পরিচর্যা দল',

    medsTitle: 'একত্রিত ঔষধ',
    medsSub: 'আপনার সমস্ত প্রেসক্রিপশন এক পরিষ্কার দৃশ্যপটে।',
    showGeneric: 'জেনেরিক নাম দেখান',
    aiUnifiedAlert: 'AI চেক: কোন ডুপ্লিকেট পাওয়া যায়নি। ব্র্যান্ড থেকে জেনেরিক রূপান্তর সমস্ত অনন্য সক্রিয় উপাদান দেখায়।',
    takeAfD: 'রাতের খাবারের পর ১টি নিন',
    takeInM: 'সকালে ১টি নিন',

    symTitle: 'লক্ষণ পরীক্ষক',
    symSub: 'আপনি কেমন অনুভব করছেন তা বর্ণনা করুন এবং আমাদের এআই পরীক্ষা করবে যে এটি আপনার বর্তমান ওষুধের সাথে সম্পর্কিত কিনা।',
    tapToSpeak: 'কথা বলতে ট্যাপ করুন',
    voiceAvailable: 'হ্যান্ডস-ফ্রি ভয়েস ইনপুট ইংরেজি, হিন্দি এবং বাংলা ভাষায় উপলব্ধ।',
    simPatient: 'আমি সকাল থেকে একটু মাথা ঘোরা অনুভব করছি এবং মুখ খুব শুষ্ক।',
    aiFound: 'এআই ঔষধ সম্পর্ক পাওয়া গেছে',
    aiSymptomMatch: 'মাথা ঘোরা এবং শুষ্ক মুখ হল লিসিনোপ্রিলের সাধারণ প্রমাণিত পার্শ্বপ্রতিক্রিয়া যা আপনি সম্প্রতি শুরু করেছেন।',
    flagSymptoms: 'ডাক্তারকে লক্ষণ সম্পর্কে জানান',

    repTitle: 'সাপ্তাহিক রিপোর্ট',
    repSub: 'আপনার স্বাস্থ্যের এআই-উত্পাদিত সারাংশ, ডাক্তারের সাথে শেয়ার করার জন্য প্রস্তুত।',
    repSummary: 'সঞ্জীব এআই ক্লিনিকাল সারাংশ',
    repWeek: 'সপ্তাহ ১৮ মার্চ - ২৪ মার্চ',
    medChanges: 'ওষুধের পরিবর্তন',
    repAdd: '১৯ শে মার্চ লিসিনোপ্রিল (10mg) যোগ করা হয়েছে',
    repComp: 'মেটফর্মিনে ১০০% সম্মতি',
    moodSym: 'মেজাজ এবং লক্ষণ সম্পর্ক',
    moodSymDesc: 'রোগী বর্ধিত চাপের মাত্রা এবং মাথা ঘোরার ৩-দিনের প্রবণতা লগ করেছে, যা ঐতিহাসিকভাবে ১৯ মার্চ লিসিনোপ্রিলের সূচনার সাথে মিলে যায়।',
    shareWithDr: 'ডাঃ স্মিথের সাথে পিডিএফ শেয়ার করুন',

    // Profile
    navProfile: 'প্রোফাইল',
    profileTitle: 'আমার প্রোফাইল',
    profileSub: 'আপনার সামগ্রিক স্বাস্থ্য ডেটা এবং অ্যাপের পছন্দগুলি পরিচালনা করুন।',
    healthId: 'স্বাস্থ্য আইডি',
    personalInfo: 'ব্যক্তিগত তথ্য',
    age32: '৩২ বছর',
    bloodType: 'রক্তের গ্রুপ',
    weightTitle: 'ওজন',
    weightLabel: '৭২ কেজি',
    medicalHistory: 'চিকিৎসার ইতিহাস',
    historyDesc: 'আপনার অতীত রোগ নির্ণয় এবং চিকিত্সার বিস্তারিত লগ দেখুন।',
    settingsPrefs: 'সেটিংস এবং পছন্দ',
    darkMode: 'ডার্ক মোড',
    notifications: 'পুশ বিজ্ঞপ্তি',
    dataPrivacy: 'ডেটা গোপনীয়তা',
    logout: 'লগ আউট',
    manageButton: 'পরিচালনা করুন'
  },
};

let currentLang = 'en';

export function t(key) {
  return (translations[currentLang] && translations[currentLang][key]) || translations.en[key] || key;
}

export function setLanguage(lang) {
  currentLang = lang;
}

export function getLanguage() {
  return currentLang;
}
