// ============================
// SANJEEV AI — Translation Engine
// ============================

const translations = {
  en: {
    // Topbar
    brandName: 'Sanjeev AI',

    // Nav
    navHome: 'Home',
    navScanner: 'Scanner',
    navTimeline: 'Timeline',
    navMood: 'Mood',

    // Home
    greeting: 'Namaste, Rahul',
    greetingSub: 'Your path to balance begins with mindful healing today.',
    safety: 'Safety',
    medSafetyScore: 'Medication Safety Score',
    scanPrescription: 'Scan Prescription',
    scanDesc: 'AI-powered analysis of all your prescriptions and medicines.',
    checkMood: 'Check Mood',
    moodDesc: 'Log your daily emotional and physical vitality balance.',
    viewAlerts: 'View Alerts',
    alertsDesc: '2 active interactions detected in your current protocol.',
    yourNextDose: 'Your Next Dose',
    withWarmWater: 'with warm water',
    markAsTaken: 'MARK AS TAKEN',
    holisticTools: 'Holistic Health Tools',
    symptomCheck: 'Symptom Check',
    mergedMeds: 'Merged Meds',
    caregiverHub: 'Caregiver Hub',
    weeklyReport: 'Weekly Report',
    interactionMap: 'Interaction Map',
    weeklyWisdom: 'Weekly Wisdom',
    insightTitle: 'The Alchemy of Brahmi for Mental Clarity',
    insightDesc: 'Learn how to pair herbal boosters with your morning meditation.',

    // Drug Interaction
    drugInteractionTitle: 'Drug Interaction Checker',
    drugInteractionSub: 'Comprehensive safety analysis for patient medication regimens.',
    patientContext: 'Patient Context',
    age: 'Age',
    knownAllergies: 'Known Allergies',
    kidneyIssue: 'Kidney Issue',
    liverIssue: 'Liver Issue',
    medicationList: 'Medication List',
    addAnother: 'Add Another',
    overallRiskScore: 'Overall Risk Score',
    low: 'Low',
    moderate: 'Moderate',
    high: 'High',
    critical: 'Critical',
    cascadePath: '1 cascade path',
    pairwise: '1 pairwise',
    cascadeDetected: 'Hidden Prescription Cascade Detected',
    gradeB: 'GRADE B',
    cascadeTechnical: 'Fluoxetine inhibits CYP2D6 enzyme blocking clearance of Metoprolol. Plasma levels rise — accumulation risk.',
    cascadeSimple: 'Fluoxetine stops your body from removing Metoprolol properly. Too much Metoprolol builds up in your blood. This can affect your heart. Tell your doctor immediately.',
    inhibitors: 'Inhibitors',
    affectedDrug: 'Affected Drug',
    safetyMapTitle: 'Safety Map™',
    liveNetwork: 'LIVE NETWORK',
    interactiveNetwork: 'Interactive drug interaction network',
    dragNodes: 'Drag nodes',
    scrollZoom: 'Scroll to zoom',
    cascadeDrug: 'Cascade drug',
    cautionDrug: 'Caution drug',
    safeDrug: 'Safe drug',
    cascadePathLegend: 'Cascade path',
    loadingMap: 'Loading Safety Map...',
    copyReport: 'Copy Report',
    exportPdf: 'Export PDF',
    alertDoctor: 'Alert Cardiologist & Psychiatrist',
    makeSimpler: 'Make Simpler',
    restoreMedical: 'Restore Medical Terms',

    // Scanner
    scannerTitle: 'Prescription Scanner',
    scannerSub: 'Point your camera at the prescription or upload a photo.',
    alignPrescription: 'Align prescription within frame',
    captureBtn: 'Capture',
    uploadBtn: 'Upload from Gallery',
    privacyNote: 'HIPAA-Ready Encryption',

    // ClearScript
    clearscriptTitle: 'ClearScript AI Extract',
    clearscriptSub: 'Our Three-Layer OCR Engine has digitized your messy prescription.',
    autoAccepted: 'Auto-Accepted (Clean read)',
    aiSuggestion: 'AI Suggestion:',
    confirm: 'Confirm',
    edit: 'Edit',
    manualFallback: 'Handwriting too messy. Manual fallback required.',
    runRiskAnalysis: 'Run Risk Analysis',

    // Bottom nav labels
    home: 'Home',
    scanner: 'Scanner',
    timeline: 'Timeline',
    mood: 'Mood',
  },

  hi: {
    brandName: 'संजीव AI',
    navHome: 'होम',
    navScanner: 'स्कैनर',
    navTimeline: 'टाइमलाइन',
    navMood: 'मूड',
    greeting: 'नमस्ते, राहुल',
    greetingSub: 'संतुलन की आपकी राह आज सचेत उपचार से शुरू होती है।',
    safety: 'सुरक्षा',
    medSafetyScore: 'दवा सुरक्षा स्कोर',
    scanPrescription: 'प्रिस्क्रिप्शन स्कैन करें',
    scanDesc: 'आपकी सभी दवाइयों का AI-संचालित विश्लेषण।',
    checkMood: 'मूड जांचें',
    moodDesc: 'अपनी दैनिक भावनात्मक और शारीरिक ऊर्जा दर्ज करें।',
    viewAlerts: 'अलर्ट देखें',
    alertsDesc: 'आपके वर्तमान प्रोटोकॉल में 2 सक्रिय अंतर्क्रियाएं पाई गईं।',
    yourNextDose: 'आपकी अगली खुराक',
    withWarmWater: 'गुनगुने पानी के साथ',
    markAsTaken: 'ली गई के रूप में चिह्नित करें',
    holisticTools: 'समग्र स्वास्थ्य उपकरण',
    symptomCheck: 'लक्षण जांच',
    mergedMeds: 'मिली हुई दवाएं',
    caregiverHub: 'देखभालकर्ता केंद्र',
    weeklyReport: 'साप्ताहिक रिपोर्ट',
    interactionMap: 'इंटरैक्शन मैप',
    weeklyWisdom: 'साप्ताहिक ज्ञान',
    insightTitle: 'मानसिक स्पष्टता के लिए ब्राह्मी का रसायन',
    insightDesc: 'जानें कि सुबह के ध्यान में हर्बल बूस्टर कैसे मिलाएं।',
    drugInteractionTitle: 'दवा अंतर्क्रिया जांचकर्ता',
    drugInteractionSub: 'रोगी दवा प्रणालियों का व्यापक सुरक्षा विश्लेषण।',
    patientContext: 'रोगी जानकारी',
    age: 'आयु',
    knownAllergies: 'ज्ञात एलर्जी',
    kidneyIssue: 'गुर्दे की समस्या',
    liverIssue: 'लिवर की समस्या',
    medicationList: 'दवाओं की सूची',
    addAnother: 'और जोड़ें',
    overallRiskScore: 'समग्र जोखिम स्कोर',
    low: 'कम',
    moderate: 'मध्यम',
    high: 'उच्च',
    critical: 'गंभीर',
    cascadePath: '1 कैस्केड पथ',
    pairwise: '1 जोड़ीवार',
    cascadeDetected: 'छिपा हुआ प्रिस्क्रिप्शन कैस्केड पकड़ा गया',
    gradeB: 'ग्रेड B',
    cascadeTechnical: 'Fluoxetine CYP2D6 एंजाइम को रोकता है जिससे Metoprolol की निकासी अवरुद्ध होती है। प्लाज्मा स्तर बढ़ता है — संचय जोखिम।',
    cascadeSimple: 'Fluoxetine आपके शरीर को Metoprolol को ठीक से हटाने से रोकता है। बहुत अधिक Metoprolol आपके खून में जमा हो जाता है। इससे आपके दिल पर असर पड़ सकता है। तुरंत अपने डॉक्टर को बताएं।',
    inhibitors: 'अवरोधक',
    affectedDrug: 'प्रभावित दवा',
    safetyMapTitle: 'सेफ्टी मैप™',
    liveNetwork: 'लाइव नेटवर्क',
    interactiveNetwork: 'इंटरैक्टिव दवा अंतर्क्रिया नेटवर्क',
    dragNodes: 'नोड्स खींचें',
    scrollZoom: 'ज़ूम करने के लिए स्क्रॉल करें',
    cascadeDrug: 'कैस्केड दवा',
    cautionDrug: 'सावधानी दवा',
    safeDrug: 'सुरक्षित दवा',
    cascadePathLegend: 'कैस्केड पथ',
    loadingMap: 'सेफ्टी मैप लोड हो रहा है...',
    copyReport: 'रिपोर्ट कॉपी करें',
    exportPdf: 'PDF निर्यात करें',
    alertDoctor: 'हृदय रोग विशेषज्ञ और मनोचिकित्सक को सतर्क करें',
    makeSimpler: 'सरल बनाएं',
    restoreMedical: 'चिकित्सा शब्द बहाल करें',
    scannerTitle: 'प्रिस्क्रिप्शन स्कैनर',
    scannerSub: 'अपना कैमरा प्रिस्क्रिप्शन पर लगाएं या फोटो अपलोड करें।',
    alignPrescription: 'प्रिस्क्रिप्शन को फ्रेम में रखें',
    captureBtn: 'कैप्चर',
    uploadBtn: 'गैलरी से अपलोड करें',
    privacyNote: 'HIPAA-तैयार एन्क्रिप्शन',
    clearscriptTitle: 'ClearScript AI अर्क',
    clearscriptSub: 'हमारे तीन-स्तरीय OCR इंजन ने आपके प्रिस्क्रिप्शन को डिजिटल कर दिया है।',
    autoAccepted: 'स्वतः स्वीकृत (स्पष्ट पठन)',
    aiSuggestion: 'AI सुझाव:',
    confirm: 'पुष्टि करें',
    edit: 'संपादित करें',
    manualFallback: 'हस्तलेख बहुत गंदा है। मैनुअल फॉलबैक आवश्यक।',
    runRiskAnalysis: 'जोखिम विश्लेषण चलाएं',
    home: 'होम',
    scanner: 'स्कैनर',
    timeline: 'टाइमलाइन',
    mood: 'मूड',
  },

  bn: {
    brandName: 'সঞ্জীব AI',
    navHome: 'হোম',
    navScanner: 'স্ক্যানার',
    navTimeline: 'টাইমলাইন',
    navMood: 'মেজাজ',
    greeting: 'নমস্কার, রাহুল',
    greetingSub: 'ভারসাম্যের পথ আজ সচেতন নিরাময় দিয়ে শুরু হয়।',
    safety: 'নিরাপত্তা',
    medSafetyScore: 'ওষুধ নিরাপত্তা স্কোর',
    scanPrescription: 'প্রেসক্রিপশন স্ক্যান করুন',
    scanDesc: 'আপনার সমস্ত ওষুধের AI-চালিত বিশ্লেষণ।',
    checkMood: 'মেজাজ পরীক্ষা করুন',
    moodDesc: 'আপনার দৈনন্দিন আবেগ এবং শারীরিক প্রাণশক্তি লিখুন।',
    viewAlerts: 'সতর্কতা দেখুন',
    alertsDesc: 'আপনার বর্তমান প্রোটোকলে ২টি সক্রিয় মিথস্ক্রিয়া সনাক্ত হয়েছে।',
    yourNextDose: 'আপনার পরের ডোজ',
    withWarmWater: 'গরম জলের সাথে',
    markAsTaken: 'নেওয়া হয়েছে হিসেবে চিহ্নিত করুন',
    holisticTools: 'সামগ্রিক স্বাস্থ্য সরঞ্জাম',
    symptomCheck: 'উপসর্গ পরীক্ষা',
    mergedMeds: 'একত্রিত ওষুধ',
    caregiverHub: 'পরিচর্যাকারী কেন্দ্র',
    weeklyReport: 'সাপ্তাহিক রিপোর্ট',
    interactionMap: 'ইন্টারঅ্যাকশন ম্যাপ',
    weeklyWisdom: 'সাপ্তাহিক জ্ঞান',
    insightTitle: 'মানসিক স্বচ্ছতার জন্য ব্রাহ্মীর রসায়ন',
    insightDesc: 'সকালের ধ্যানে ভেষজ বুস্টার কেমন করে যোগ করবেন তা শিখুন।',
    drugInteractionTitle: 'ওষুধ মিথস্ক্রিয়া পরীক্ষক',
    drugInteractionSub: 'রোগীর ওষুধ ব্যবস্থার ব্যাপক নিরাপত্তা বিশ্লেষণ।',
    patientContext: 'রোগীর তথ্য',
    age: 'বয়স',
    knownAllergies: 'পরিচিত অ্যালার্জি',
    kidneyIssue: 'কিডনি সমস্যা',
    liverIssue: 'লিভার সমস্যা',
    medicationList: 'ওষুধের তালিকা',
    addAnother: 'আরো যোগ করুন',
    overallRiskScore: 'সামগ্রিক ঝুঁকি স্কোর',
    low: 'কম',
    moderate: 'মাঝারি',
    high: 'উচ্চ',
    critical: 'জটিল',
    cascadePath: '১টি ক্যাসকেড পথ',
    pairwise: '১টি জোড়াবদ্ধ',
    cascadeDetected: 'লুকানো প্রেসক্রিপশন ক্যাসকেড সনাক্ত হয়েছে',
    gradeB: 'গ্রেড B',
    cascadeTechnical: 'Fluoxetine CYP2D6 এনজাইম বাধা দেয় যা Metoprolol এর ক্লিয়ারেন্স রোধ করে। প্লাজমা মাত্রা বাড়ে — সঞ্চয় ঝুঁকি।',
    cascadeSimple: 'Fluoxetine আপনার শরীরকে Metoprolol সঠিকভাবে অপসারণ করতে বাধা দেয়। অতিরিক্ত Metoprolol আপনার রক্তে জমা হয়। এটি আপনার হৃদয়ে প্রভাব ফেলতে পারে। অবিলম্বে আপনার ডাক্তারকে জানান।',
    inhibitors: 'বাধাদানকারী',
    affectedDrug: 'প্রভাবিত ওষুধ',
    safetyMapTitle: 'সেফটি ম্যাপ™',
    liveNetwork: 'লাইভ নেটওয়ার্ক',
    interactiveNetwork: 'ইন্টারেক্টিভ ওষুধ মিথস্ক্রিয়া নেটওয়ার্ক',
    dragNodes: 'নোড টানুন',
    scrollZoom: 'জুম করতে স্ক্রল করুন',
    cascadeDrug: 'ক্যাসকেড ওষুধ',
    cautionDrug: 'সতর্কতা ওষুধ',
    safeDrug: 'নিরাপদ ওষুধ',
    cascadePathLegend: 'ক্যাসকেড পথ',
    loadingMap: 'সেফটি ম্যাপ লোড হচ্ছে...',
    copyReport: 'রিপোর্ট কপি করুন',
    exportPdf: 'PDF রপ্তানি করুন',
    alertDoctor: 'হৃদরোগ বিশেষজ্ঞ ও মনোচিকিৎসককে সতর্ক করুন',
    makeSimpler: 'সহজ করুন',
    restoreMedical: 'চিকিৎসা পদ পুনরুদ্ধার করুন',
    scannerTitle: 'প্রেসক্রিপশন স্ক্যানার',
    scannerSub: 'আপনার ক্যামেরা প্রেসক্রিপশনের দিকে নির্দেশ করুন বা ছবি আপলোড করুন।',
    alignPrescription: 'প্রেসক্রিপশন ফ্রেমের মধ্যে রাখুন',
    captureBtn: 'ক্যাপচার',
    uploadBtn: 'গ্যালারি থেকে আপলোড',
    privacyNote: 'HIPAA-প্রস্তুত এনক্রিপশন',
    clearscriptTitle: 'ClearScript AI নির্যাস',
    clearscriptSub: 'আমাদের তিন-স্তরের OCR ইঞ্জিন আপনার প্রেসক্রিপশন ডিজিটাইজ করেছে।',
    autoAccepted: 'স্বয়ংক্রিয়ভাবে গৃহীত (পরিষ্কার পড়া)',
    aiSuggestion: 'AI পরামর্শ:',
    confirm: 'নিশ্চিত করুন',
    edit: 'সম্পাদনা করুন',
    manualFallback: 'হাতের লেখা খুব অস্পষ্ট। ম্যানুয়াল ফলব্যাক প্রয়োজন।',
    runRiskAnalysis: 'ঝুঁকি বিশ্লেষণ চালান',
    home: 'হোম',
    scanner: 'স্ক্যানার',
    timeline: 'টাইমলাইন',
    mood: 'মেজাজ',
  },
};

let currentLang = 'en';

export function t(key) {
  return (translations[currentLang] && translations[currentLang][key]) || translations.en[key] || key;
}

export function setLanguage(lang) {
  currentLang = lang;
}

export function getLanguage() {
  return currentLang;
}
